        f.write("define config.name = _(\"Cybernovels\")\n")
        f.write("define config.version = \"1.0\"\n")
        f.write("define config.has_sound = False\n")
        f.write("define config.has_music = False\n")
        f.write("define config.has_voice = False\n")
        f.write("\n")
        f.write("# The game starts here.\n")
        f.write("label start:\n")
        f.write("    call chapter_1thesignalinthenoiseindexchapter1thesignalinthenoise\n") # Jump to the first proper chapter
        f.write("    jump end_game\n")
        f.write("\n")
        f.write("label end_game:\n")
        f.write("    \"The End.\"\n")
        f.write("    return\n")
