# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y build-essential libcurl4-openssl-dev python3-dev python3-pip
  SHELL
end
