# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.network "forwarded_port", guest: 8099, host: 8099

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus   = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -e
    apt-get update -qq
    apt-get install -y -q \
      build-essential libcurl4-openssl-dev \
      python3-dev python3-venv python3-pip \
      patchelf ccache curl git

    # Install gem lang if binary present in /vagrant
    if [ -f /vagrant/gem ]; then
      cp /vagrant/gem /usr/local/bin/gem
      chmod +x /usr/local/bin/gem
    fi

    cd /vagrant
    make deps
    make all
    echo "==> VM ready. Run: vagrant ssh -c 'cd /vagrant && ./hontrade'"
  SHELL
end
